In [1]:
import numpy as np

##### Create the array

In [7]:
x = np.array([56,12,35,48,71,11,28])

In [8]:
print(x)

[56 12 35 48 71 11 28]


In [9]:
type(x)

numpy.ndarray

In [10]:
x.ndim

1

In [11]:
x

array([56, 12, 35, 48, 71, 11, 28])

In [12]:
x.dtype

dtype('int32')

In [20]:
x=np.array([56,12,35,48,71,11,28], dtype = np.uint8)

In [21]:
x

array([56, 12, 35, 48, 71, 11, 28], dtype=uint8)

In [22]:

x[0] =100

In [23]:
x

array([100,  12,  35,  48,  71,  11,  28], dtype=uint8)

In [24]:
x[0] = 145

In [25]:
x

array([145,  12,  35,  48,  71,  11,  28], dtype=uint8)

In [26]:
x.size

7

In [27]:
x.shape

(7,)

In [28]:
x.std()

43.33260072640789

In [29]:
x.sum()

350

In [34]:
y = np.array([67,89,45.34,34,69,11,35])

In [35]:
y

array([67.  , 89.  , 45.34, 34.  , 69.  , 11.  , 35.  ])

In [37]:
y.dtype

dtype('float64')

In [38]:
z = np.array([67,89,45.34,69,11,True])

In [45]:
z

array([67.  , 89.  , 45.34, 69.  , 11.  ,  1.  ])

In [46]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
np.arange(4,10)

array([4, 5, 6, 7, 8, 9])

In [50]:
np.arange(2,20,3)

array([ 2,  5,  8, 11, 14, 17])

In [52]:
np.arange(20,1,-3)

array([20, 17, 14, 11,  8,  5,  2])

In [53]:
np.arange(0, 10, 0.33)

array([0.  , 0.33, 0.66, 0.99, 1.32, 1.65, 1.98, 2.31, 2.64, 2.97, 3.3 ,
       3.63, 3.96, 4.29, 4.62, 4.95, 5.28, 5.61, 5.94, 6.27, 6.6 , 6.93,
       7.26, 7.59, 7.92, 8.25, 8.58, 8.91, 9.24, 9.57, 9.9 ])

In [54]:
np.arange(10,30,4)

array([10, 14, 18, 22, 26])

In [56]:
np.linspace(1,11,5)

array([ 1. ,  3.5,  6. ,  8.5, 11. ])

##### Array Operations

In [57]:
num1 = np.array([56,12,33,14,68,99])
num2 = np.array([28,28,19,39,38,74])

In [58]:
num1+10

array([ 66,  22,  43,  24,  78, 109])

In [59]:
num1*4

array([224,  48, 132,  56, 272, 396])

In [60]:
num2/5

array([ 5.6,  5.6,  3.8,  7.8,  7.6, 14.8])

In [61]:
[56,12,33,14,68,99]*3

[56, 12, 33, 14, 68, 99, 56, 12, 33, 14, 68, 99, 56, 12, 33, 14, 68, 99]

In [62]:
num1 - num2

array([ 28, -16,  14, -25,  30,  25])

In [63]:
num1 + num2

array([ 84,  40,  52,  53, 106, 173])

##### Matrix

In [69]:
m = np.array([[4,6,7],[1,2,3],[8,0,2,],[9,3,5]])

In [70]:
m.dtype

dtype('int32')

In [71]:
m.shape

(4, 3)

In [72]:
m.size

12

In [73]:
m.ndim

2

In [74]:
m[2][1]

0

In [75]:
m[2,1]

0

In [76]:
m

array([[4, 6, 7],
       [1, 2, 3],
       [8, 0, 2],
       [9, 3, 5]])

In [77]:
m[1:3, 0:2]

array([[1, 2],
       [8, 0]])

In [79]:
m1 = m.reshape(3,4)
m1

array([[4, 6, 7, 1],
       [2, 3, 8, 0],
       [2, 9, 3, 5]])

In [80]:
m.reshape(6,2)

array([[4, 6],
       [7, 1],
       [2, 3],
       [8, 0],
       [2, 9],
       [3, 5]])

In [82]:
m[1:3, 0:2] = np.array([[7,8],[1,1]])
m

array([[4, 6, 7],
       [7, 8, 3],
       [1, 1, 2],
       [9, 3, 5]])

In [83]:
m.reshape(2,-1)

array([[4, 6, 7, 7, 8, 3],
       [1, 1, 2, 9, 3, 5]])

In [84]:
m.reshape(-1)

array([4, 6, 7, 7, 8, 3, 1, 1, 2, 9, 3, 5])

In [85]:
m.flatten()

array([4, 6, 7, 7, 8, 3, 1, 1, 2, 9, 3, 5])

In [86]:
m.T

array([[4, 7, 1, 9],
       [6, 8, 1, 3],
       [7, 3, 2, 5]])

In [87]:
m.min()

1

In [88]:
m.min(axis=1)

array([4, 3, 1, 3])

In [89]:
m.min(axis=0)

array([1, 1, 2])

In [90]:
m.max(axis=1)

array([7, 8, 2, 9])

In [91]:
m.sum(axis=0)

array([21, 18, 17])

In [92]:
y

array([67.  , 89.  , 45.34, 34.  , 69.  , 11.  , 35.  ])

In [98]:
m.argmax()

9

In [99]:
m

array([[4, 6, 7],
       [7, 8, 3],
       [1, 1, 2],
       [9, 3, 5]])

In [100]:
y.argmax()

1

In [101]:
y

array([67.  , 89.  , 45.34, 34.  , 69.  , 11.  , 35.  ])

In [102]:
m.dtype

dtype('int32')

In [103]:
m = m.astype(np.float16)
m

array([[4., 6., 7.],
       [7., 8., 3.],
       [1., 1., 2.],
       [9., 3., 5.]], dtype=float16)

In [104]:
x

array([145,  12,  35,  48,  71,  11,  28], dtype=uint8)

In [105]:
y=x

In [106]:
y

array([145,  12,  35,  48,  71,  11,  28], dtype=uint8)

In [107]:
y[0] = 20

In [108]:
x

array([20, 12, 35, 48, 71, 11, 28], dtype=uint8)

In [110]:
id(y)

1204020590608

In [111]:
id(x)

1204020590608

In [112]:
y=x.copy()
y


array([20, 12, 35, 48, 71, 11, 28], dtype=uint8)

In [113]:
y[0] = 30

In [114]:
x

array([20, 12, 35, 48, 71, 11, 28], dtype=uint8)

In [115]:
y

array([30, 12, 35, 48, 71, 11, 28], dtype=uint8)

In [117]:
id(y)

1204036296144

In [118]:
id(x)

1204020590608